/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as MainLayoutProfileRouteImport } from './routes/_mainLayout/profile'
import { Route as MainLayoutRecipeIndexRouteImport } from './routes/_mainLayout/recipe.index'
import { Route as MainLayoutRecipeIdRouteImport } from './routes/_mainLayout/recipe.$id'

const ManagementIndexLazyRouteImport = createFileRoute('/management/')()
const MainLayoutIndexLazyRouteImport = createFileRoute('/_mainLayout/')()
const ManagementUnitsLazyRouteImport = createFileRoute('/management/units')()
const ManagementKitchenwareLazyRouteImport = createFileRoute(
  '/management/kitchenware',
)()
const ManagementIngredientsLazyRouteImport = createFileRoute(
  '/management/ingredients',
)()
const MainLayoutPlansLazyRouteImport = createFileRoute('/_mainLayout/plans')()

const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementIndexLazyRoute = ManagementIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementRoute,
} as any).lazy(() =>
  import('./routes/management/index.lazy').then((d) => d.Route),
)
const MainLayoutIndexLazyRoute = MainLayoutIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_mainLayout/index.lazy').then((d) => d.Route),
)
const ManagementUnitsLazyRoute = ManagementUnitsLazyRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => ManagementRoute,
} as any).lazy(() =>
  import('./routes/management/units.lazy').then((d) => d.Route),
)
const ManagementKitchenwareLazyRoute =
  ManagementKitchenwareLazyRouteImport.update({
    id: '/kitchenware',
    path: '/kitchenware',
    getParentRoute: () => ManagementRoute,
  } as any).lazy(() =>
    import('./routes/management/kitchenware.lazy').then((d) => d.Route),
  )
const ManagementIngredientsLazyRoute =
  ManagementIngredientsLazyRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => ManagementRoute,
  } as any).lazy(() =>
    import('./routes/management/ingredients.lazy').then((d) => d.Route),
  )
const MainLayoutPlansLazyRoute = MainLayoutPlansLazyRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_mainLayout/plans.lazy').then((d) => d.Route),
)
const MainLayoutProfileRoute = MainLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutRecipeIndexRoute = MainLayoutRecipeIndexRouteImport.update({
  id: '/recipe/',
  path: '/recipe/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutRecipeIdRoute = MainLayoutRecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => MainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexLazyRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRouteWithChildren
  '/profile': typeof MainLayoutProfileRoute
  '/plans': typeof MainLayoutPlansLazyRoute
  '/management/ingredients': typeof ManagementIngredientsLazyRoute
  '/management/kitchenware': typeof ManagementKitchenwareLazyRoute
  '/management/units': typeof ManagementUnitsLazyRoute
  '/management/': typeof ManagementIndexLazyRoute
  '/recipe/$id': typeof MainLayoutRecipeIdRoute
  '/recipe/': typeof MainLayoutRecipeIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof MainLayoutProfileRoute
  '/plans': typeof MainLayoutPlansLazyRoute
  '/management/ingredients': typeof ManagementIngredientsLazyRoute
  '/management/kitchenware': typeof ManagementKitchenwareLazyRoute
  '/management/units': typeof ManagementUnitsLazyRoute
  '/': typeof MainLayoutIndexLazyRoute
  '/management': typeof ManagementIndexLazyRoute
  '/recipe/$id': typeof MainLayoutRecipeIdRoute
  '/recipe': typeof MainLayoutRecipeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/management': typeof ManagementRouteWithChildren
  '/_mainLayout/profile': typeof MainLayoutProfileRoute
  '/_mainLayout/plans': typeof MainLayoutPlansLazyRoute
  '/management/ingredients': typeof ManagementIngredientsLazyRoute
  '/management/kitchenware': typeof ManagementKitchenwareLazyRoute
  '/management/units': typeof ManagementUnitsLazyRoute
  '/_mainLayout/': typeof MainLayoutIndexLazyRoute
  '/management/': typeof ManagementIndexLazyRoute
  '/_mainLayout/recipe/$id': typeof MainLayoutRecipeIdRoute
  '/_mainLayout/recipe/': typeof MainLayoutRecipeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/management'
    | '/profile'
    | '/plans'
    | '/management/ingredients'
    | '/management/kitchenware'
    | '/management/units'
    | '/management/'
    | '/recipe/$id'
    | '/recipe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/plans'
    | '/management/ingredients'
    | '/management/kitchenware'
    | '/management/units'
    | '/'
    | '/management'
    | '/recipe/$id'
    | '/recipe'
  id:
    | '__root__'
    | '/_mainLayout'
    | '/login'
    | '/management'
    | '/_mainLayout/profile'
    | '/_mainLayout/plans'
    | '/management/ingredients'
    | '/management/kitchenware'
    | '/management/units'
    | '/_mainLayout/'
    | '/management/'
    | '/_mainLayout/recipe/$id'
    | '/_mainLayout/recipe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManagementRoute: typeof ManagementRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/': {
      id: '/management/'
      path: '/'
      fullPath: '/management/'
      preLoaderRoute: typeof ManagementIndexLazyRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/management/units': {
      id: '/management/units'
      path: '/units'
      fullPath: '/management/units'
      preLoaderRoute: typeof ManagementUnitsLazyRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/kitchenware': {
      id: '/management/kitchenware'
      path: '/kitchenware'
      fullPath: '/management/kitchenware'
      preLoaderRoute: typeof ManagementKitchenwareLazyRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/ingredients': {
      id: '/management/ingredients'
      path: '/ingredients'
      fullPath: '/management/ingredients'
      preLoaderRoute: typeof ManagementIngredientsLazyRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/_mainLayout/plans': {
      id: '/_mainLayout/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof MainLayoutPlansLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/profile': {
      id: '/_mainLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainLayoutProfileRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/recipe/': {
      id: '/_mainLayout/recipe/'
      path: '/recipe'
      fullPath: '/recipe/'
      preLoaderRoute: typeof MainLayoutRecipeIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/recipe/$id': {
      id: '/_mainLayout/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof MainLayoutRecipeIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainLayoutProfileRoute: typeof MainLayoutProfileRoute
  MainLayoutPlansLazyRoute: typeof MainLayoutPlansLazyRoute
  MainLayoutIndexLazyRoute: typeof MainLayoutIndexLazyRoute
  MainLayoutRecipeIdRoute: typeof MainLayoutRecipeIdRoute
  MainLayoutRecipeIndexRoute: typeof MainLayoutRecipeIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutProfileRoute: MainLayoutProfileRoute,
  MainLayoutPlansLazyRoute: MainLayoutPlansLazyRoute,
  MainLayoutIndexLazyRoute: MainLayoutIndexLazyRoute,
  MainLayoutRecipeIdRoute: MainLayoutRecipeIdRoute,
  MainLayoutRecipeIndexRoute: MainLayoutRecipeIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

interface ManagementRouteChildren {
  ManagementIngredientsLazyRoute: typeof ManagementIngredientsLazyRoute
  ManagementKitchenwareLazyRoute: typeof ManagementKitchenwareLazyRoute
  ManagementUnitsLazyRoute: typeof ManagementUnitsLazyRoute
  ManagementIndexLazyRoute: typeof ManagementIndexLazyRoute
}

const ManagementRouteChildren: ManagementRouteChildren = {
  ManagementIngredientsLazyRoute: ManagementIngredientsLazyRoute,
  ManagementKitchenwareLazyRoute: ManagementKitchenwareLazyRoute,
  ManagementUnitsLazyRoute: ManagementUnitsLazyRoute,
  ManagementIndexLazyRoute: ManagementIndexLazyRoute,
}

const ManagementRouteWithChildren = ManagementRoute._addFileChildren(
  ManagementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ManagementRoute: ManagementRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
